- DocumentID: murex_config_dir
  Title: >-
    `MUREX_CONFIG_DIR` (str)
  CategoryID: variables
  SubCategoryIDs: [ vars.profile ]
  Summary: >-
    Defines the path to Murex's config
  Description: |-
    `MUREX_CONFIG_DIR` should be set outside of Murex and then passed to Murex upon
    its start up.

    {{ include "gen/includes/vars-murex-profile.inc.md" }}
  Detail:
  Synonyms:
  - murex_config_dir
  - MUREX_CONFIG_DIR
  Related:
  - profile
  - MUREX_HISTORY
  - MUREX_PROFILE
  - MUREX_PRELOAD
  - MUREX_MODULES
