name: Murex Tests

on:
  push:
    paths:
      - "**/*.go"

  workflow_dispatch:

jobs:
  Murex-Tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23', "1.24", "1.25" ]
    env:
      MUREX_BUILD_FLAGS: --no-colour
      MUREX_TEST_NO_EXEC_DEPS: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: |
          go version

      - name: Build
        run: |
          make install

      - name: Test
        run: |
          make test

      - name: Build cross-compiled targets
        run: |
          ./bin/murex ./test/build_all_platforms.mx --no-colour

      - name: Build web assembly target
        run: |
          GOOS=js GOARCH=wasm go build -o murex.wasm .